node_modules/object-fit-images/dist/ofi.browser.js:
	npm install --save object-fit-images

image-viewer.css: image-viewer.styl helpers.styl theme-fixes.styl
	stylus < image-viewer.styl > $@


.PHONY: clean

clean:
	-rm image-viewer.css
